"""add_privacy_presets

Revision ID: 5f66737c3e67
Revises: 825b82c49cf4
Create Date: 2026-05-20 13:52:55.862540

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = "5f66737c3e67"
down_revision: Union[str, Sequence[str], None] = "825b82c49cf4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "privacypreset",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("page_path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("settings", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_privacypreset_name"), "privacypreset", ["name"], unique=False
    )
    op.create_index(
        op.f("ix_privacypreset_page_path"), "privacypreset", ["page_path"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_privacypreset_page_path"), table_name="privacypreset")
    op.drop_index(op.f("ix_privacypreset_name"), table_name="privacypreset")
    op.drop_table("privacypreset")
    # ### end Alembic commands ###
