"""sync_schema

Revision ID: 6eb672772864
Revises: 5f66737c3e67
Create Date: 2026-05-20 17:09:59.535479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '6eb672772864'
down_revision: Union[str, Sequence[str], None] = '5f66737c3e67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobfilament',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('filament_id', sa.Integer(), nullable=False),
    sa.Column('grams_used', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['filament_id'], ['filament.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['printjob.id'], ),
    sa.PrimaryKeyConstraint('job_id', 'filament_id')
    )
    op.add_column('printjob', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('printjob', sa.Column('job_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('printjob', sa.Column('production_cost', sa.Float(), nullable=False))
    op.create_index(op.f('ix_printjob_name'), 'printjob', ['name'], unique=False)
    op.drop_constraint(op.f('printjob_filament_id_fkey'), 'printjob', type_='foreignkey')
    op.drop_column('printjob', 'filament_id')
    op.drop_column('printjob', 'power_usage_kwh')
    op.drop_column('printjob', 'used_filament_g')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('printjob', sa.Column('used_filament_g', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('printjob', sa.Column('power_usage_kwh', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('printjob', sa.Column('filament_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('printjob_filament_id_fkey'), 'printjob', 'filament', ['filament_id'], ['id'])
    op.drop_index(op.f('ix_printjob_name'), table_name='printjob')
    op.drop_column('printjob', 'production_cost')
    op.drop_column('printjob', 'job_type')
    op.drop_column('printjob', 'name')
    op.drop_table('jobfilament')
    # ### end Alembic commands ###
